[Settings]
ID = "Ramkumar Shankar"

# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://ramkumarshankar.netlify.com/*"
  to = "http://ramkumar.me/:splat"
  status = 301
  force = true
